#!/bin/bash
# Push to GitHub - Run this script to complete the upload

echo "=========================================="
echo "PUSHING TO GITHUB"
echo "=========================================="
echo ""
echo "Repository: https://github.com/ss-arch/testtransactionbot"
echo "Branch: main"
echo "Files: 25 files (3,265 lines)"
echo ""
echo "=========================================="
echo ""

# Check if we're authenticated
echo "Attempting to push..."
echo ""

git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "=========================================="
    echo "✅ SUCCESS! Repository pushed to GitHub"
    echo "=========================================="
    echo ""
    echo "View your repository at:"
    echo "https://github.com/ss-arch/testtransactionbot"
    echo ""
else
    echo ""
    echo "=========================================="
    echo "⚠️  AUTHENTICATION REQUIRED"
    echo "=========================================="
    echo ""
    echo "You need to authenticate with GitHub."
    echo ""
    echo "OPTION 1: Use Personal Access Token (Recommended)"
    echo "--------------------------------------------"
    echo "1. Go to: https://github.com/settings/tokens"
    echo "2. Click 'Generate new token (classic)'"
    echo "3. Give it a name: 'Transaction Monitor Bot'"
    echo "4. Select scope: ✓ repo"
    echo "5. Click 'Generate token'"
    echo "6. Copy the token"
    echo "7. Run this script again"
    echo "8. When prompted for password, paste your token"
    echo ""
    echo "OPTION 2: Use GitHub CLI"
    echo "--------------------------------------------"
    echo "gh auth login"
    echo "gh repo view ss-arch/testtransactionbot"
    echo "git push -u origin main"
    echo ""
    echo "OPTION 3: Use SSH"
    echo "--------------------------------------------"
    echo "# Generate SSH key"
    echo "ssh-keygen -t ed25519 -C \"ss@dexpa.io\""
    echo ""
    echo "# Add to GitHub"
    echo "cat ~/.ssh/id_ed25519.pub"
    echo "# Copy the output and add it to:"
    echo "# https://github.com/settings/ssh/new"
    echo ""
    echo "# Update remote to use SSH"
    echo "git remote set-url origin git@github.com:ss-arch/testtransactionbot.git"
    echo "git push -u origin main"
    echo ""
fi
